# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."
# toolchain = "nightly-2020-09-28"
# docker_image = "jjy0/ckb-capsule-recipe-rust:2020-9-28"

# capsule version
version = "0.4.4"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "index"
template_type = "Rust"

[[contracts]]
name = "config"
template_type = "Rust"

[[contracts]]
name = "type_lock"
template_type = "Rust"

[[contracts]]
name = "cdp"
template_type = "Rust"

[[contracts]]
name = "token"
template_type = "Rust"

[[contracts]]
name = "always_success"
template_type = "Rust"

[[contracts]]
name = "debt"
template_type = "Rust"

[[contracts]]
name = "auction"
template_type = "Rust"

[[contracts]]
name = "sys_debt"
template_type = "Rust"

[[contracts]]
name = "dao_info"
template_type = "Rust"

[[contracts]]
name = "burn_lock"
template_type = "Rust"

[[contracts]]
name = "udt_owner"
template_type = "Rust"